version: '3.8'
services:
  postgres:
    image: postgres:13.3
    container_name: postgres_container
    environment:
     POSTGRES_USER: ${POSTGRES_USER}
     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
     POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tennis-network


  tennis_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: tennis_scoreboard:latest
    container_name: tennis_container
    ports:
      - "${APP_PORT}:8080"
    environment:
      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_SHOW_SQL: ${DB_SHOW_SQL}
      DB_DDL_AUTO: ${DB_DDL_AUTO}
    depends_on:
      - postgres
    networks:
      - tennis-network

networks:
  tennis-network:
    driver: bridge
volumes:
  postgres_data: