# JDBC connection properties
hibernate.connection.driver_class=org.postgresql.Driver
hibernate.connection.url={DB_URL}
hibernate.connection.username=${DB_USER}
hibernate.connection.password=${DB_PASSWORD}

# Dialect
hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# SQL logging
hibernate.show_sql=${DB_SHOW_SQL:true}
hibernate.format_sql=true
hibernate.highlight_sql=true
hibernate.use_sql_comments=true
hibernate.type=trace

# Session context
hibernate.current_session_context_class=thread

# DDL auto-management
hibernate.hbm2ddl.auto=${DB_DDL_AUTO:update}


## JDBC connection properties
#hibernate.connection.driver_class=org.postgresql.Driver
#hibernate.connection.url=jdbc:postgresql://localhost:5432/tennis_scoreboard
#hibernate.connection.username=java_user
#hibernate.connection.password=java_password
#
## Dialect
#hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#
## SQL logging
#hibernate.show_sql=true
#hibernate.format_sql=true
#hibernate.highlight_sql=true
#hibernate.use_sql_comments=true
#hibernate.type=trace
#
## Session context
#hibernate.current_session_context_class=thread
#
## DDL auto-management
#hibernate.hbm2ddl.auto=update